version: '3.8'
services:
  yaygara:
    build:
      context: https://github.com/mertskaplan/yaygara.git
      dockerfile: Dockerfile
    container_name: yaygara
    ports:
      - "8622:80"
    restart: unless-stopped