version: '3.8'
services:
  guessplosion:
    build:
      context: https://github.com/mertskaplan/guessplosion.git
      dockerfile: Dockerfile
    container_name: guessplosion
    ports:
      - "8622:80"
    restart: unless-stopped